apiVersion: v1
kind: Service
metadata:
  name: siteconsultas
  labels:
    run: siteconsultas
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: siteconsultas
