apiVersion: v1
kind: Service
metadata:
  name: siteconsultas-db
  labels:
    run: siteconsultas-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: siteconsultas-db
